export const STAGES = [
  {
    id: 'stage1',
    order: 1,
    lang: 'ko',
    name: '기본자리',
    keys: ['a', 's', 'd', 'f', 'g', 'h', 'j', 'k', 'l', ';'],
    unlock: null
  },
  {
    id: 'stage2',
    order: 2,
    lang: 'ko',
    name: '윗자리',
    keys: ['q', 'w', 'e', 'r', 't', 'y', 'u', 'i', 'o', 'p'],
    unlock: { stageId: 'stage1', minKpm: 100 }
  },
  {
    id: 'stage3',
    order: 3,
    lang: 'ko',
    name: '아랫자리',
    keys: ['z', 'x', 'c', 'v', 'b', 'n', 'm', ',', '.', '/'],
    unlock: { stageId: 'stage2', minKpm: 100 }
  },
  {
    id: 'stage4',
    order: 4,
    lang: 'ko',
    name: '짧은글',
    keys: [],
    unlock: { stageId: 'stage3', minKpm: 120 }
  },
  {
    id: 'en1',
    order: 5,
    lang: 'en',
    name: '기본자리',
    keys: ['a', 's', 'd', 'f', 'g', 'h', 'j', 'k', 'l', ';'],
    unlock: null
  },
  {
    id: 'en2',
    order: 6,
    lang: 'en',
    name: '윗자리',
    keys: ['q', 'w', 'e', 'r', 't', 'y', 'u', 'i', 'o', 'p'],
    unlock: { stageId: 'en1', minKpm: 100 }
  },
  {
    id: 'en3',
    order: 7,
    lang: 'en',
    name: '아랫자리',
    keys: ['z', 'x', 'c', 'v', 'b', 'n', 'm', ',', '.', '/'],
    unlock: { stageId: 'en2', minKpm: 100 }
  },
  {
    id: 'en4',
    order: 8,
    lang: 'en',
    name: '짧은글',
    keys: [],
    unlock: { stageId: 'en3', minKpm: 120 }
  }
];

// 트랙(한글/영어) 안에서의 단계 번호와 접두어
export function getStageLabel(stage) {
  const track = STAGES.filter((item) => item.lang === stage.lang);
  const number = track.findIndex((item) => item.id === stage.id) + 1;
  const prefix = stage.lang === 'en' ? '영어' : '한글';
  return { number, prefix };
}

// ══════════════════════════════════════════════════════
// 1단계 — 기본자리
// 초성: ㅁ(a) ㄴ(s) ㅇ(d) ㄹ(f) ㅎ(g)
// 중성: ㅏ(k) ㅓ(j) ㅗ(h) ㅣ(l)
// ══════════════════════════════════════════════════════
export const TEXTS = {
  stage1: [
    '나 아 오 이 어',
    '마 나 라 하 이',
    '이 어 아 오 나',
    '하 라 나 이 아',
    '라 이 아 나 하',
    '오 나 이 라 하',
    '이 나 아 하 오',
    '나 아 이 오 하',
    '나라 아이 하나',
    '이마 머리 이모',
    '오리 나이 이리',
    '아나 리나 이나',
    '마리 아리 나리',
    '나이 이마 이모',
    '하나 이리 오리',
    '이모 아이 나이',
    '나날 홀로 이마',
    '온 나라 하나',
    '어머니 나란히',
    '할머니 이모 나',
    '나란히 이마 나',
    '홀로 어머니 나',
    '할머니 나이 나',
    '날 말 알 올 얼',
    '한 안 인 란 만',
    '힘 님 함 남 홍',
    '일 날 알 홀 할',
    '허 히 하 호',
    '너 나 노 니',
    '머 모 미 마',
    '러 로 리 라',
    '나라 이마 이모',
    '머리 나이 하나',
    '이마 어머니 나이',
    '아이 이모 나란히',
    '이마 나이 할머니',
    '하나 나라 이모',
    '나이 아이 나라 이마',
    '올 얼 일 알 날',
    '힘 님 남 함',
    '이마 나이 나란히',
    '어머니 나란히 나이',
    '할머니 이모 나란히',
    '홀로 이마 나이',
    '날 알 이마 하나',
    '나날 이마 나이',
    '한 인 나라 하나',
    '아이 이모 나이 나라',
    '오리 이리 나이 이마',
    '머리 이마 나이 아이',
    '어머니 이모 나이 아이',
    '나라 하나 이마 이모',
    '이리 오리 나이 하나',
    '할머니 어머니 나이',
    '나란히 홀로 이마',
    '나날 나란히 이마',
    '온 나라 이마 하나',
    '아이 나이 이마 머리',
    '이모 어머니 나이 이마',
    '나라 아이 이마 이모 나이',
  ],

  // ══════════════════════════════════════════════════════
  // 2단계 — 윗자리 포함
  // 추가 초성: ㅂ(q) ㅈ(w) ㄷ(e) ㄱ(r) ㅅ(t)
  // 추가 중성: ㅛ(y) ㅕ(u) ㅑ(i) ㅐ(o) ㅔ(p)
  // ══════════════════════════════════════════════════════
  stage2: [
    // 동물
    '강아지 나비 고양이',
    '기린 사자 가오리',
    '기러기 나비 강아지',
    '도마뱀 가오리 기린',
    '개 새 기러기 나비',
    '사자 기린 나비 개',
    '고양이 강아지 새',
    '기러기 사자 도마뱀',
    // 식물·자연
    '개나리 진달래 나비',
    '해바라기 개나리 새',
    '진달래 모래 바다',
    '소나기 바다 개나리',
    '도라지 진달래 나비',
    '해바라기 도라지 봄',
    '봄 소나기 모래',
    '개나리 해바라기 봄',
    // 가족·감정
    '아버지 동생 이야기',
    '선생님 가족 사랑',
    '사랑 행복 가족',
    '기억 비밀 이야기',
    '아버지 선생님 사랑',
    '동생 가족 행복',
    '이야기 기억 사랑',
    '비밀 행복 이야기',
    // 학교·물건
    '학교 가방 도서관',
    '교과서 가방 달리기',
    '도서관 배낭 학교',
    '가방 교과서 선생님',
    '배낭 도서관 사랑',
    '달리기 놀이 가요',
    '학교 선생님 교과서',
    '도서관 배낭 이야기',
    // 음식·과일
    '사과 바나나 고기',
    '배 고기 사과',
    '과자 바나나 배',
    '오렌지 사과 배',
    '바나나 오렌지 고기',
    '과일 사과 오렌지',
    '고기 과자 바나나',
    '배 오렌지 사과',
    // 위치·방향
    '여기 저기 거리',
    '가로 세로 바다',
    '서로 도로 거리',
    '여기서 저기서',
    '가도 나도 서도',
    '도리 소리 거리',
    '가로 세로 서로',
    '도로 거리 바다',
    // 혼합
    '강아지 사과 바다',
    '기린 개나리 사랑',
    '나비 행복 소나기',
    '사자 배 가방',
    '학교 나비 사랑',
    '선생님 개나리 이야기',
    '기억 강아지 바다',
    '가족 나비 행복',
    '개나리 학교 사랑',
    '아버지 바나나 기억',
    '바람 가요 노래',
    '소개 이야기 여행',
    '달리기 놀이 사랑',
    '비밀 기억 가족',
  ],

  // ══════════════════════════════════════════════════════
  // 3단계 — 아랫자리 포함 (전체 키 사용)
  // 추가 초성: ㅋ(z) ㅌ(x) ㅊ(c) ㅍ(v)
  // 추가 중성: ㅠ(b) ㅜ(n) ㅡ(m)
  // ══════════════════════════════════════════════════════
  stage3: [
    // 스포츠·놀이
    '친구 축구 수영',
    '태권도 줄넘기 달리기',
    '자전거 수영 친구',
    '축구 태권도 줄넘기',
    '수영 자전거 달리기',
    '줄넘기 축구 태권도',
    '친구 자전거 축구',
    '달리기 수영 줄넘기',
    // 과일
    '수박 포도 참외',
    '레몬 파인애플 아보카도',
    '아보카도 수박 포도',
    '참외 레몬 파인애플',
    '파인애플 아보카도 포도',
    '레몬 참외 수박',
    '수박 파인애플 레몬',
    '포도 참외 아보카도',
    // 음식·간식
    '초코 치즈 피자',
    '라면 갈비 두부',
    '피자 초코 라면',
    '고구마 감자 두부',
    '치즈 피자 갈비',
    '라면 고구마 초코',
    '감자 두부 갈비',
    '피자 고구마 치즈',
    // 자연·날씨
    '구름 무지개 태풍',
    '파도 바람 구름',
    '무지개 하늘 파도',
    '바람 태풍 무지개',
    '하늘 구름 파도',
    '파도 하늘 바람',
    '태풍 파도 구름',
    '무지개 바람 하늘',
    // 학용품
    '연필 공책 지우개',
    '색연필 공책 연필',
    '지우개 스케치북 연필',
    '색연필 지우개 공책',
    '연필 스케치북 색연필',
    '지우개 공책 스케치북',
    '공책 연필 색연필',
    '스케치북 지우개 연필',
    // 옷·신발
    '신발 모자 장갑',
    '구두 운동화 바지',
    '이불 신발 모자',
    '장갑 구두 운동화',
    '바지 이불 모자',
    '모자 바지 신발',
    '운동화 장갑 구두',
    '이불 바지 신발',
    // 악기·기기
    '피아노 기타 노트북',
    '기타 피아노 노트북',
    '노트북 기타 피아노',
    '피아노 노트북 기타',
    // 혼합
    '친구 수박 구름',
    '축구 포도 무지개',
    '수영 치즈 바람',
    '태권도 레몬 하늘',
    '줄넘기 피자 파도',
    '자전거 아보카도 구름',
    '신발 모자 수박',
    '연필 초코 친구',
    '피아노 포도 수영',
    '공책 무지개 축구',
    '고구마 태풍 파도',
    '장갑 레몬 자전거',
  ],

  // ══════════════════════════════════════════════════════
  // 4단계 — 짧은글
  // ══════════════════════════════════════════════════════
  stage4: [
    // 학교 생활
    '나는 학교에 간다',
    '선생님이 좋아요',
    '우리 반은 사이 좋아',
    '오늘 수업이 재미있어',
    '방과 후에 같이 놀자',
    '도서관에서 책을 읽어요',
    '수학 공부가 재미있어',
    '교과서를 잘 챙겼어요',
    '선생님께 인사해요',
    '학교 끝나고 뭐 할까',
    // 날씨·자연
    '오늘 날씨가 맑다',
    '하늘이 파랗고 맑아요',
    '봄 여름 가을 겨울',
    '무지개가 떴어요',
    '구름이 두둥실 떠요',
    '오늘따라 바람이 시원해',
    '비가 오면 우산을 써요',
    '눈이 오면 눈사람 만들자',
    '꽃이 피고 나비가 날아요',
    '노란 개나리가 피었어요',
    // 가족·일상
    '사랑해요 우리 가족',
    '엄마랑 같이 요리해요',
    '아빠와 자전거를 탔어요',
    '할머니 댁에 놀러 갔어',
    '동생이랑 같이 놀았어요',
    '밥을 맛있게 먹었어요',
    '이를 깨끗이 닦아야 해',
    '일찍 자고 일찍 일어나요',
    '가족과 함께 여행을 갔어',
    '우리 가족은 사이가 좋아',
    // 음식
    '점심에 피자를 먹었어요',
    '수박이 달고 시원해요',
    '초코 아이스크림이 좋아',
    '라면을 맛있게 끓였어요',
    '오늘 점심은 무엇을 먹을까',
    '사과랑 바나나가 맛있어',
    '과자보다 과일이 좋아요',
    '엄마가 갈비를 구워 줬어',
    // 스포츠·취미
    '타자 연습을 열심히 해요',
    '축구가 정말 재미있어',
    '수영장에서 수영했어요',
    '줄넘기를 백 번 했어요',
    '자전거를 신나게 탔어요',
    '태권도를 배우고 싶어',
    '나는 그림 그리기를 좋아해',
    '피아노 연습을 열심히 해',
    '책 읽기를 좋아해요',
    '친구와 축구를 했어요',
    // 다짐·응원
    '열심히 공부했어요',
    '오늘도 힘차게 해보자',
    '포기하지 말고 해보자',
    '차근차근 연습해 봐요',
    '잘 할 수 있어 파이팅',
    '매일 조금씩 연습해요',
    '한 글자 한 글자 열심히',
    '착하고 바른 어린이',
    '친구들과 사이좋게 지내요',
    '우리 함께 노래해요',
  ],

  // ══════════════════════════════════════════════════════
  // 영어 1단계 — 기본자리 (a s d f g h j k l)
  // ══════════════════════════════════════════════════════
  en1: [
    'asdf jkl;',
    'aa ss dd ff',
    'jj kk ll ;;',
    'fj dk sl a;',
    'ad as fa da',
    'ja ka la ha',
    'gag hah dad',
    'sad lad gas',
    'ask all add',
    'fall hall gall',
    'glad flag lass',
    'dash gash sash',
    'as has gas',
    'dad had a lad',
    'a sad lad',
    'all fall hall',
    'ask a lad',
    'dad has a flag',
    'a glass fall',
    'add a salad',
    'alas a gala',
    'half a glass',
    'a lass had salad',
    'flags fall fast',
    'dads ask lads',
    'sal has a flask',
  ],

  // ══════════════════════════════════════════════════════
  // 영어 2단계 — 윗자리 포함 (q w e r t y u i o p 추가)
  // ══════════════════════════════════════════════════════
  en2: [
    'we are here',
    'you are okay',
    'water is sweet',
    'a happy tiger',
    'the tree is tall',
    'i like apples',
    'a red rose',
    'they play a lot',
    'we go to the park',
    'a little house',
    'she reads a story',
    'the sky is grey',
    'we ride a horse',
    'a yellow flower',
    'the fire is hot',
    'you write well',
    'a quiet lake',
    'we sail out west',
    'take your paper',
    'the door is white',
    'a sweet potato',
    'we eat together',
    'the girl is happy',
    'a fast walker',
    'stars are pretty',
    'you did great work',
    'a warm sweater',
    'the world is wide',
  ],

  // ══════════════════════════════════════════════════════
  // 영어 3단계 — 아랫자리 포함 (전체 키)
  // ══════════════════════════════════════════════════════
  en3: [
    'a black cat',
    'the brown fox',
    'a big zebra',
    'monkeys eat bananas',
    'the moon is bright',
    'seven blue balloons',
    'a cozy blanket',
    'we bake a cake',
    'the bus is coming',
    'jump very high',
    'a quick brown fox',
    'pizza and juice',
    'my new bicycle',
    'a funny monkey',
    'the clock ticks',
    'candy and cookies',
    'a magic wizard',
    'the zoo is open',
    'six brave boys',
    'a violin and a cello',
    'winter is very cold',
    'my very best friend',
    'the ocean is deep',
    'a lazy dog naps',
    'we climb the mountain',
    'a dozen crayons',
  ],

  // ══════════════════════════════════════════════════════
  // 영어 4단계 — 짧은글
  // ══════════════════════════════════════════════════════
  en4: [
    'I like to play soccer',
    'The sun is shining today',
    'My dog runs very fast',
    'We read books at school',
    'She sings a happy song',
    'The cat sleeps on the sofa',
    'I want some ice cream',
    'Birds fly high in the sky',
    'We are best friends forever',
    'My mom makes good food',
    'The rainbow has many colors',
    'I can ride my bike now',
    'Winter snow is white and cold',
    'Let us go to the beach',
    'The stars shine at night',
    'I love my family so much',
    'A frog jumps into the pond',
    'We plant flowers in spring',
    'The train goes very fast',
    'Practice makes perfect every day',
    'You can do it if you try',
    'Today is a wonderful day',
  ],
};
